spring:
  datasource:
    url:  jdbc:mysql://81.68.234.49:3306
    username: miniprogram
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080

mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true